"""Execute SQL payload files through Supabase MCP execute_sql using stdio MCP client.

Reads output/mcp_call_*.json files generated by apply_sql_files.py and invokes
the Supabase execute_sql tool for each payload in order.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def load_calls(directory: Path) -> list[dict]:
    files = sorted(directory.glob("mcp_call_*.json"), key=lambda p: p.name)
    calls = []
    for path in files:
        calls.append(json.loads(path.read_text(encoding="utf-8")))
    return calls


def main() -> int:
    base = Path(__file__).resolve().parent / "output"
    calls = load_calls(base)
    if not calls:
        print("No mcp_call_*.json files found in output/", file=sys.stderr)
        return 1

    for idx, call in enumerate(calls, start=1):
        args = call["arguments"]
        query = args["query"]
        print(f"[{idx}/{len(calls)}] project={args['project_id']} query_chars={len(query)}")

    print(
        "\nRun these through Supabase MCP execute_sql (plugin-supabase-supabase).",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
